<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrefectureSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('prefectures')->insert([
            ['id' => 1, 'region_id' => 4, 'id_prefectures' => 17, 'nom' => 'RABAT'],
            ['id' => 2, 'region_id' => 4, 'id_prefectures' => 20, 'nom' => 'SKHIRATE-TEMARA'],
            ['id' => 3, 'region_id' => 4, 'id_prefectures' => 21, 'nom' => 'KHEMISSET'],
            ['id' => 4, 'region_id' => 6, 'id_prefectures' => 30, 'nom' => 'MOHAMMADIA'],
            ['id' => 5, 'region_id' => 9, 'id_prefectures' => 31, 'nom' => 'AGADIR IDA OUTANANE'],
            ['id' => 6, 'region_id' => 9, 'id_prefectures' => 32, 'nom' => 'INEZGANE-AIT MELLOUL'],
            ['id' => 7, 'region_id' => 9, 'id_prefectures' => 33, 'nom' => 'CHTOUKA-AIT BAHA'],
            ['id' => 8, 'region_id' => 9, 'id_prefectures' => 34, 'nom' => 'TAROUDANNT'],
            ['id' => 9, 'region_id' => 9, 'id_prefectures' => 35, 'nom' => 'TIZNIT'],
            ['id' => 10, 'region_id' => 8, 'id_prefectures' => 36, 'nom' => 'OUARZAZATE'],
            ['id' => 11, 'region_id' => 8, 'id_prefectures' => 37, 'nom' => 'ZAGOURA'],
            ['id' => 12, 'region_id' => 1, 'id_prefectures' => 38, 'nom' => 'AL HOCEIMA'],
            ['id' => 13, 'region_id' => 3, 'id_prefectures' => 39, 'nom' => 'TAZA'],
            ['id' => 14, 'region_id' => 3, 'id_prefectures' => 40, 'nom' => 'TAOUNATE'],
            ['id' => 15, 'region_id' => 5, 'id_prefectures' => 41, 'nom' => 'BENI MELLAL'],
            ['id' => 16, 'region_id' => 5, 'id_prefectures' => 42, 'nom' => 'AZILAL'],
            ['id' => 17, 'region_id' => 3, 'id_prefectures' => 46, 'nom' => 'SEFROU'],
            ['id' => 18, 'region_id' => 3, 'id_prefectures' => 47, 'nom' => 'BOULEMANE'],
            ['id' => 19, 'region_id' => 10, 'id_prefectures' => 48, 'nom' => 'GUELMIM'],
            ['id' => 20, 'region_id' => 9, 'id_prefectures' => 49, 'nom' => 'TATA'],
            ['id' => 21, 'region_id' => 10, 'id_prefectures' => 50, 'nom' => 'ASSA-ZAG'],
            ['id' => 22, 'region_id' => 11, 'id_prefectures' => 51, 'nom' => 'ES-SEMARA'],
            ['id' => 23, 'region_id' => 10, 'id_prefectures' => 52, 'nom' => 'TAN-TAN'],
            ['id' => 24, 'region_id' => 4, 'id_prefectures' => 53, 'nom' => 'KENITRA'],
            ['id' => 25, 'region_id' => 4, 'id_prefectures' => 54, 'nom' => 'SIDI KACEM'],
            ['id' => 26, 'region_id' => 11, 'id_prefectures' => 55, 'nom' => 'LAAYOUNE'],
            ['id' => 27, 'region_id' => 11, 'id_prefectures' => 56, 'nom' => 'BOUJDOUR'],
            ['id' => 28, 'region_id' => 7, 'id_prefectures' => 60, 'nom' => 'CHICHAOUA'],
            ['id' => 29, 'region_id' => 7, 'id_prefectures' => 61, 'nom' => 'AL HAOUZ'],
            ['id' => 30, 'region_id' => 7, 'id_prefectures' => 62, 'nom' => 'EL KELAA DES SRAGHNA'],
            ['id' => 31, 'region_id' => 7, 'id_prefectures' => 63, 'nom' => 'ESSAOUIRA'],
            ['id' => 32, 'region_id' => 3, 'id_prefectures' => 66, 'nom' => 'EL HAJEB'],
            ['id' => 33, 'region_id' => 3, 'id_prefectures' => 67, 'nom' => 'IFRANE'],
            ['id' => 34, 'region_id' => 5, 'id_prefectures' => 68, 'nom' => 'KHENIFRA'],
            ['id' => 35, 'region_id' => 8, 'id_prefectures' => 69, 'nom' => 'ERRACHIDIA'],
            ['id' => 36, 'region_id' => 12, 'id_prefectures' => 70, 'nom' => 'OUED ED DAHAB'],
            ['id' => 37, 'region_id' => 12, 'id_prefectures' => 71, 'nom' => 'AOUSSERD'],
            ['id' => 38, 'region_id' => 2, 'id_prefectures' => 72, 'nom' => 'OUJDA-ANGAD'],
            ['id' => 39, 'region_id' => 2, 'id_prefectures' => 73, 'nom' => 'JERADA'],
            ['id' => 40, 'region_id' => 2, 'id_prefectures' => 74, 'nom' => 'BERKANE'],
            ['id' => 41, 'region_id' => 2, 'id_prefectures' => 75, 'nom' => 'TAOURIRT'],
            ['id' => 42, 'region_id' => 2, 'id_prefectures' => 76, 'nom' => 'FIGUIG'],
            ['id' => 43, 'region_id' => 2, 'id_prefectures' => 77, 'nom' => 'NADOR'],
            ['id' => 44, 'region_id' => 7, 'id_prefectures' => 78, 'nom' => 'SAFI'],
            ['id' => 45, 'region_id' => 6, 'id_prefectures' => 79, 'nom' => 'EL JADIDA'],
            ['id' => 46, 'region_id' => 6, 'id_prefectures' => 80, 'nom' => 'SETTAT'],
            ['id' => 47, 'region_id' => 5, 'id_prefectures' => 81, 'nom' => 'KHOURIBGA'],
            ['id' => 48, 'region_id' => 6, 'id_prefectures' => 82, 'nom' => 'BENSLIMANE'],
            ['id' => 49, 'region_id' => 1, 'id_prefectures' => 83, 'nom' => 'TANGER-ASSILAH'],
            ['id' => 50, 'region_id' => 1, 'id_prefectures' => 85, 'nom' => 'TETOUAN'],
            ['id' => 51, 'region_id' => 1, 'id_prefectures' => 86, 'nom' => 'LARACHE'],
            ['id' => 52, 'region_id' => 1, 'id_prefectures' => 87, 'nom' => 'CHEFCHAOUEN'],
            ['id' => 53, 'region_id' => 4, 'id_prefectures' => 1701, 'nom' => 'SALE'],
            ['id' => 54, 'region_id' => 6, 'id_prefectures' => 1702, 'nom' => 'CASABLANCA'],
            ['id' => 55, 'region_id' => 6, 'id_prefectures' => 1703, 'nom' => 'HAY HASSANI'],
            ['id' => 56, 'region_id' => 6, 'id_prefectures' => 1704, 'nom' => 'AIN CHOCK'],
            ['id' => 57, 'region_id' => 6, 'id_prefectures' => 1705, 'nom' => 'SIDI BERNOUSSI'],
            ['id' => 58, 'region_id' => 6, 'id_prefectures' => 1706, 'nom' => 'BEN M\'SICK'],
            ['id' => 59, 'region_id' => 6, 'id_prefectures' => 1707, 'nom' => 'MOULAY RACHID'],
            ['id' => 60, 'region_id' => 3, 'id_prefectures' => 1708, 'nom' => 'FES'],
            ['id' => 61, 'region_id' => 6, 'id_prefectures' => 1709, 'nom' => 'NOUACEUR'],
            ['id' => 62, 'region_id' => 3, 'id_prefectures' => 1710, 'nom' => 'MOULAY YACOUB'],
            ['id' => 63, 'region_id' => 7, 'id_prefectures' => 1711, 'nom' => 'MARRAKECH'],
            ['id' => 64, 'region_id' => 6, 'id_prefectures' => 1712, 'nom' => 'MEDIOUNA'],
            ['id' => 65, 'region_id' => 3, 'id_prefectures' => 1713, 'nom' => 'MEKNES'],
            ['id' => 66, 'region_id' => 1, 'id_prefectures' => 1714, 'nom' => 'FAHS-ANJARA'],
            ['id' => 67, 'region_id' => 6, 'id_prefectures' => 1715, 'nom' => 'CASABLANCA ANFA'],
            ['id' => 68, 'region_id' => 6, 'id_prefectures' => 1716, 'nom' => 'AL FIDA MERS SULTA'],
            ['id' => 69, 'region_id' => 6, 'id_prefectures' => 1717, 'nom' => 'AIN SEBAA HAY MOHAMMADI'],
            ['id' => 70, 'region_id' => 1, 'id_prefectures' => 1792, 'nom' => 'M\'DIQ - FNIDQ'],
            ['id' => 71, 'region_id' => 10, 'id_prefectures' => 2028, 'nom' => 'SIDI IFNI'],
            ['id' => 72, 'region_id' => 8, 'id_prefectures' => 2029, 'nom' => 'TINGHIR'],
            ['id' => 73, 'region_id' => 2, 'id_prefectures' => 2030, 'nom' => 'GUERCIF'],
            ['id' => 74, 'region_id' => 5, 'id_prefectures' => 2031, 'nom' => 'FQUIH BEN SALAH'],
            ['id' => 75, 'region_id' => 4, 'id_prefectures' => 2032, 'nom' => 'SIDI SLIMANE'],
            ['id' => 76, 'region_id' => 1, 'id_prefectures' => 2033, 'nom' => 'OUEZZANE'],
            ['id' => 77, 'region_id' => 11, 'id_prefectures' => 2034, 'nom' => 'TARFAYA'],
            ['id' => 78, 'region_id' => 7, 'id_prefectures' => 2035, 'nom' => 'REHAMNA'],
            ['id' => 79, 'region_id' => 8, 'id_prefectures' => 2036, 'nom' => 'MIDELT'],
            ['id' => 80, 'region_id' => 2, 'id_prefectures' => 2037, 'nom' => 'DRIOUCH'],
            ['id' => 81, 'region_id' => 7, 'id_prefectures' => 2038, 'nom' => 'YOUSSOUFIA'],
            ['id' => 82, 'region_id' => 6, 'id_prefectures' => 2039, 'nom' => 'SIDI BENNOUR'],
            ['id' => 83, 'region_id' => 6, 'id_prefectures' => 2040, 'nom' => 'BERRECHID']
        ]);
    }
}
