<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VilleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('villes')->insert([
            ['id' => 1, 'nom' => 'Aarab Sebbah Gheris'],
            ['id' => 2, 'nom' => 'Imi Ouaddar'],
            ['id' => 3, 'nom' => 'Aarab Sebbah Ziz'],
            ['id' => 4, 'nom' => 'Abdelghaya Souahel'],
            ['id' => 5, 'nom' => 'Adar'],
            ['id' => 6, 'nom' => 'Abadou'],
            ['id' => 7, 'nom' => 'Abaynou'],
            ['id' => 8, 'nom' => 'Abbou Lakhal'],
            ['id' => 9, 'nom' => 'Abteh'],
            ['id' => 10, 'nom' => 'Adrej'],
            ['id' => 11, 'nom' => 'Aferkat'],
            ['id' => 12, 'nom' => 'Afourar'],
            ['id' => 13, 'nom' => 'Adaghas'],
            ['id' => 14, 'nom' => 'Agafay'],
            ['id' => 15, 'nom' => 'Agdz'],
            ['id' => 16, 'nom' => 'Aghbal'],
            ['id' => 17, 'nom' => 'Agadir'],
            ['id' => 18, 'nom' => 'Agadir Melloul'],
            ['id' => 19, 'nom' => 'Aghbala'],
            ['id' => 20, 'nom' => 'Aghbalou'],
            ['id' => 21, 'nom' => 'Aghouinite'],
            ['id' => 22, 'nom' => 'Agourai'],
            ['id' => 23, 'nom' => 'Aghbalou Nkerdous'],
            ['id' => 24, 'nom' => 'Ahlaf'],
            ['id' => 25, 'nom' => 'Ahfir'],
            ['id' => 26, 'nom' => 'Aguelmous'],
            ['id' => 27, 'nom' => 'Ahl Sidi Lahcen'],
            ['id' => 28, 'nom' => 'Ain Attig'],
            ['id' => 29, 'nom' => 'Ain Bni Mathar'],
            ['id' => 30, 'nom' => 'Ain Erreggada'],
            ['id' => 31, 'nom' => 'Ain Cheggag'],
            ['id' => 32, 'nom' => 'Ain Johra'],
            ['id' => 33, 'nom' => 'Ain Harrouda'],
            ['id' => 34, 'nom' => 'Ain Legdah'],
            ['id' => 35, 'nom' => 'Ain Aouda'],
            ['id' => 36, 'nom' => 'Ahmar Laglalcha'],
            ['id' => 37, 'nom' => 'Ain Leuh'],
            ['id' => 38, 'nom' => 'Ain Karma'],
            ['id' => 39, 'nom' => 'Ain Orma'],
            ['id' => 40, 'nom' => 'Ain Taoujdate'],
            ['id' => 41, 'nom' => 'Ait Amira'],
            ['id' => 42, 'nom' => 'Ait Baha'],
            ['id' => 43, 'nom' => 'Ain Sfa'],
            ['id' => 44, 'nom' => 'Ain Tizgha'],
            ['id' => 45, 'nom' => 'Ain Sbit'],
            ['id' => 46, 'nom' => 'Aït Iaaza'],
            ['id' => 47, 'nom' => 'Ait Bouyahya El Hajjama'],
            ['id' => 48, 'nom' => 'Ait Imour'],
            ['id' => 49, 'nom' => 'Ait Belkacem'],
            ['id' => 50, 'nom' => 'Ait Ben Yacoub'],
            ['id' => 51, 'nom' => 'Ait Boubidmane'],
            ['id' => 52, 'nom' => 'Ait Milk'],
            ['id' => 53, 'nom' => 'Ait Melloul'],
            ['id' => 54, 'nom' => 'Ait Mimoun'],
            ['id' => 55, 'nom' => 'Ait Ichou'],
            ['id' => 56, 'nom' => 'Ait Ishaq'],
            ['id' => 57, 'nom' => 'Ait Malek'],
            ['id' => 58, 'nom' => 'Ait Yaazem'],
            ['id' => 59, 'nom' => 'Ait Sidi Daoud'],
            ['id' => 60, 'nom' => 'Ait Yadine'],
            ['id' => 61, 'nom' => 'Ait Youl'],
            ['id' => 62, 'nom' => 'Ait Ouallal'],
            ['id' => 63, 'nom' => 'Ait Ourir'],
            ['id' => 64, 'nom' => 'Ain Bida'],
            ['id' => 65, 'nom' => 'Ait Ouribel'],
            ['id' => 66, 'nom' => 'Akka'],
            ['id' => 67, 'nom' => 'Akhfennir'],
            ['id' => 68, 'nom' => 'Aklim'],
            ['id' => 69, 'nom' => 'Al Aaroui'],
            ['id' => 70, 'nom' => 'Aknoul'],
            ['id' => 71, 'nom' => 'Al Firdaous'],
            ['id' => 72, 'nom' => 'Ajdir'],
            ['id' => 73, 'nom' => 'Akarma'],
            ['id' => 74, 'nom' => 'Alnif'],
            ['id' => 75, 'nom' => 'Al Hoceima'],
            ['id' => 76, 'nom' => 'El Aioun Sidi Mellouk'],
            ['id' => 77, 'nom' => 'Amerzgane'],
            ['id' => 78, 'nom' => 'Ameur Seflia'],
            ['id' => 79, 'nom' => 'Al Haouz'],
            ['id' => 80, 'nom' => 'Amalou'],
            ['id' => 81, 'nom' => 'Allyene'],
            ['id' => 82, 'nom' => 'Amskroud'],
            ['id' => 83, 'nom' => 'Amtar'],
            ['id' => 84, 'nom' => 'Anfeg'],
            ['id' => 85, 'nom' => 'Anjra'],
            ['id' => 86, 'nom' => 'Aoulouz'],
            ['id' => 87, 'nom' => 'Amghras'],
            ['id' => 88, 'nom' => 'Aousserd'],
            ['id' => 89, 'nom' => 'Amezmiz'],
            ['id' => 90, 'nom' => 'Aquouass Briech'],
            ['id' => 91, 'nom' => 'Arbaoua'],
            ['id' => 92, 'nom' => 'Arbaa Sahel'],
            ['id' => 93, 'nom' => 'Arekmane'],
            ['id' => 94, 'nom' => 'Arfoud'],
            ['id' => 95, 'nom' => 'Aourir'],
            ['id' => 96, 'nom' => 'Aqesri'],
            ['id' => 97, 'nom' => 'Assa'],
            ['id' => 98, 'nom' => 'Azemmour'],
            ['id' => 99, 'nom' => 'Ayir'],
            ['id' => 100, 'nom' => 'Assa zag'],
            ['id' => 101, 'nom' => 'Azilal'],
            ['id' => 102, 'nom' => 'Asni'],
            ['id' => 103, 'nom' => 'Asilah'],
            ['id' => 104, 'nom' => 'Assahrij'],
            ['id' => 105, 'nom' => 'Bab Berred'],
            ['id' => 106, 'nom' => 'Azrou'],
            ['id' => 107, 'nom' => 'Bab Taza'],
            ['id' => 108, 'nom' => 'Bejaad'],
            ['id' => 109, 'nom' => 'Barkine'],
            ['id' => 110, 'nom' => 'Belfaa'],
            ['id' => 111, 'nom' => 'Azlaf'],
            ['id' => 112, 'nom' => 'Azla'],
            ['id' => 113, 'nom' => 'Ben Guerir'],
            ['id' => 114, 'nom' => 'Béni Yakhlef'],
            ['id' => 115, 'nom' => 'Béni Mellal'],
            ['id' => 116, 'nom' => 'Ben Ahmed'],
            ['id' => 117, 'nom' => 'Beni Malek'],
            ['id' => 118, 'nom' => 'Ben Taieb'],
            ['id' => 119, 'nom' => 'Berkane'],
            ['id' => 120, 'nom' => 'Bhalil'],
            ['id' => 121, 'nom' => 'Benslimane'],
            ['id' => 122, 'nom' => 'Ben Smim'],
            ['id' => 123, 'nom' => 'Ben Maachou'],
            ['id' => 124, 'nom' => 'Bir Ennasr'],
            ['id' => 125, 'nom' => 'Bir Tam Tam'],
            ['id' => 126, 'nom' => 'Bir Jdid'],
            ['id' => 127, 'nom' => 'Bitit'],
            ['id' => 128, 'nom' => 'Bizdad'],
            ['id' => 129, 'nom' => 'Bni Ansar'],
            ['id' => 130, 'nom' => 'Bin El Ouidane'],
            ['id' => 131, 'nom' => 'Berrechid'],
            ['id' => 132, 'nom' => 'Biougra'],
            ['id' => 133, 'nom' => 'Bni Bouzra'],
            ['id' => 134, 'nom' => 'Bni Ftah'],
            ['id' => 135, 'nom' => 'Bni Harchen'],
            ['id' => 136, 'nom' => 'Bni Hassane'],
            ['id' => 137, 'nom' => 'Bni Ayat'],
            ['id' => 138, 'nom' => 'Bni Khloug'],
            ['id' => 139, 'nom' => 'Bni Tadjite'],
            ['id' => 140, 'nom' => 'Bni Drar'],
            ['id' => 141, 'nom' => 'Bni Chiker'],
            ['id' => 142, 'nom' => 'Bouarfa'],
            ['id' => 143, 'nom' => 'Boudnib'],
            ['id' => 144, 'nom' => 'Boudinar'],
            ['id' => 145, 'nom' => 'Bouanane'],
            ['id' => 146, 'nom' => 'Bouadel'],
            ['id' => 147, 'nom' => 'Boughriba'],
            ['id' => 148, 'nom' => 'Bouguedra'],
            ['id' => 149, 'nom' => 'Bouizakarne'],
            ['id' => 150, 'nom' => 'Boujniba'],
            ['id' => 151, 'nom' => 'Bni Salah'],
            ['id' => 152, 'nom' => 'Boufkrane'],
            ['id' => 153, 'nom' => 'Bni Marghnine'],
            ['id' => 154, 'nom' => 'Bni Mathar'],
            ['id' => 155, 'nom' => 'Boujdour'],
            ['id' => 156, 'nom' => 'Boulanouar'],
            ['id' => 157, 'nom' => 'Boulaouane'],
            ['id' => 158, 'nom' => 'Boulemane'],
            ['id' => 159, 'nom' => 'Boumalne-Dades'],
            ['id' => 160, 'nom' => 'Boumia'],
            ['id' => 161, 'nom' => 'Bounaamane'],
            ['id' => 162, 'nom' => 'Bouskoura'],
            ['id' => 163, 'nom' => 'Boukhalef'],
            ['id' => 164, 'nom' => 'Bousselham'],
            ['id' => 165, 'nom' => 'Bouzemmour'],
            ['id' => 166, 'nom' => 'Bouznika'],
            ['id' => 167, 'nom' => 'Bradia'],
            ['id' => 168, 'nom' => 'Brachoua'],
            ['id' => 169, 'nom' => 'Bsara'],
            ['id' => 170, 'nom' => 'Cap de leau'],
            ['id' => 171, 'nom' => 'Cabo Negro'],
            ['id' => 172, 'nom' => 'Casablanca'],
            ['id' => 173, 'nom' => 'Chakrane'],
            ['id' => 174, 'nom' => 'Chefchaouen'],
            ['id' => 175, 'nom' => 'Chaibate'],
            ['id' => 176, 'nom' => 'Cherrat'],
            ['id' => 177, 'nom' => 'Chellalate'],
            ['id' => 178, 'nom' => 'Chichaoua'],
            ['id' => 179, 'nom' => 'Chouihia'],
            ['id' => 180, 'nom' => 'Chtouka'],
            ['id' => 181, 'nom' => 'Dakhla'],
            ['id' => 182, 'nom' => 'Daoura'],
            ['id' => 183, 'nom' => 'Dar Bni Karrich'],
            ['id' => 184, 'nom' => 'Dar Bel Amri'],
            ['id' => 185, 'nom' => 'Dar Chaffai'],
            ['id' => 186, 'nom' => 'Dar Bouazza'],
            ['id' => 187, 'nom' => 'Dar Gueddari'],
            ['id' => 188, 'nom' => 'Dar El Kebdani'],
            ['id' => 189, 'nom' => 'Dar Ould Zidouh'],
            ['id' => 190, 'nom' => 'Dar Jamaa'],
            ['id' => 191, 'nom' => 'Dcheira'],
            ['id' => 192, 'nom' => 'Dcheïra El Jihadia'],
            ['id' => 193, 'nom' => 'Debdou'],
            ['id' => 194, 'nom' => 'Demnate'],
            ['id' => 195, 'nom' => 'Deroua'],
            ['id' => 196, 'nom' => 'Dir El Ksiba'],
            ['id' => 197, 'nom' => 'Drargua'],
            ['id' => 198, 'nom' => 'Driouch'],
            ['id' => 199, 'nom' => 'Dzouz'],
            ['id' => 200, 'nom' => 'Echemmaia'],
            ['id' => 201, 'nom' => 'El Gara'],
            ['id' => 202, 'nom' => 'El Beddouza'],
            ['id' => 203, 'nom' => 'El Borouj'],
            ['id' => 204, 'nom' => 'El Foqra'],
            ['id' => 205, 'nom' => 'El Hajeb'],
            ['id' => 206, 'nom' => 'El Guerdane'],
            ['id' => 207, 'nom' => 'El Hanchane'],
            ['id' => 208, 'nom' => 'El Jebha'],
            ['id' => 209, 'nom' => 'El Jadida'],
            ['id' => 210, 'nom' => 'El Kelâa des Sraghna'],
            ['id' => 211, 'nom' => 'El Ksiba'],
            ['id' => 212, 'nom' => 'El Majjatia Ouled Taleb'],
            ['id' => 213, 'nom' => 'El Marsa'],
            ['id' => 214, 'nom' => 'El Menzeh'],
            ['id' => 215, 'nom' => 'El Mansouria'],
            ['id' => 216, 'nom' => 'El Maader El Kabir'],
            ['id' => 217, 'nom' => 'El Menzel'],
            ['id' => 218, 'nom' => 'El Outia'],
            ['id' => 219, 'nom' => 'Errachidia'],
            ['id' => 220, 'nom' => 'Errahma'],
            ['id' => 221, 'nom' => 'Er-Rich'],
            ['id' => 222, 'nom' => 'Er-Rissani'],
            ['id' => 223, 'nom' => 'Es-Semara'],
            ['id' => 224, 'nom' => 'Essaouira'],
            ['id' => 225, 'nom' => 'Ezzhiliga'],
            ['id' => 226, 'nom' => 'Farkhana'],
            ['id' => 227, 'nom' => 'Fask'],
            ['id' => 228, 'nom' => 'Fès'],
            ['id' => 229, 'nom' => 'Fdalate'],
            ['id' => 230, 'nom' => 'Fezouane'],
            ['id' => 231, 'nom' => 'Fezouata'],
            ['id' => 232, 'nom' => 'Figuig'],
            ['id' => 233, 'nom' => 'Foum El Oued'],
            ['id' => 234, 'nom' => 'Fnideq'],
            ['id' => 235, 'nom' => 'Foum Oudi'],
            ['id' => 236, 'nom' => 'Foum zguid'],
            ['id' => 237, 'nom' => 'Foum Jemaa'],
            ['id' => 238, 'nom' => 'Fezna'],
            ['id' => 239, 'nom' => 'Freija'],
            ['id' => 240, 'nom' => 'Galaz'],
            ['id' => 241, 'nom' => 'Ghafsai'],
            ['id' => 242, 'nom' => 'Ghiata Al Gharbia'],
            ['id' => 243, 'nom' => 'Ghmate'],
            ['id' => 244, 'nom' => 'Goulmima'],
            ['id' => 245, 'nom' => 'Fquih Ben Saleh'],
            ['id' => 246, 'nom' => 'Gueznaia'],
            ['id' => 247, 'nom' => 'Guigou'],
            ['id' => 248, 'nom' => 'Guisser'],
            ['id' => 249, 'nom' => 'Gzenaya Al Janoubia'],
            ['id' => 250, 'nom' => 'Had Bouhssoussen'],
            ['id' => 251, 'nom' => 'Had Boumoussa'],
            ['id' => 252, 'nom' => 'Guenfouda'],
            ['id' => 253, 'nom' => 'Guelmim'],
            ['id' => 254, 'nom' => 'Guercif'],
            ['id' => 255, 'nom' => 'Had Kourt'],
            ['id' => 256, 'nom' => 'Had Soualem'],
            ['id' => 257, 'nom' => 'Haouzia'],
            ['id' => 258, 'nom' => 'Hassi Berkane'],
            ['id' => 259, 'nom' => 'Hattane'],
            ['id' => 260, 'nom' => 'Houara Oulad Raho'],
            ['id' => 261, 'nom' => 'Houderrane'],
            ['id' => 262, 'nom' => 'Hrara'],
            ['id' => 263, 'nom' => 'Iferni'],
            ['id' => 264, 'nom' => 'Had Dra'],
            ['id' => 265, 'nom' => 'Ifrane'],
            ['id' => 266, 'nom' => 'Ifrane Atlas Saghir'],
            ['id' => 267, 'nom' => 'Ighrem Nougdal'],
            ['id' => 268, 'nom' => 'Ijoukak'],
            ['id' => 269, 'nom' => 'Imider'],
            ['id' => 270, 'nom' => 'Imindounit'],
            ['id' => 271, 'nom' => 'Imintanoute'],
            ['id' => 272, 'nom' => 'Imoulass'],
            ['id' => 273, 'nom' => 'Imlil'],
            ['id' => 274, 'nom' => 'Imouzzer'],
            ['id' => 275, 'nom' => 'Imouzzer-Kendar'],
            ['id' => 276, 'nom' => 'Imrabten'],
            ['id' => 277, 'nom' => 'Imouzzer Marmoucha'],
            ['id' => 278, 'nom' => 'Imsouane'],
            ['id' => 279, 'nom' => 'Imzouren'],
            ['id' => 280, 'nom' => 'Inchaden'],
            ['id' => 281, 'nom' => 'Inzegan'],
            ['id' => 282, 'nom' => 'Irohalen'],
            ['id' => 283, 'nom' => 'Iqaddar'],
            ['id' => 284, 'nom' => 'Issafen'],
            ['id' => 285, 'nom' => 'Issaguen'],
            ['id' => 286, 'nom' => 'Issen'],
            ['id' => 287, 'nom' => 'Itzer'],
            ['id' => 288, 'nom' => 'Izemmouren'],
            ['id' => 289, 'nom' => 'Jaadar'],
            ['id' => 290, 'nom' => 'Jaidate'],
            ['id' => 291, 'nom' => 'Jamaat Shaim'],
            ['id' => 292, 'nom' => 'Jbel Lahbib'],
            ['id' => 293, 'nom' => 'Jemaa Shaim'],
            ['id' => 294, 'nom' => 'Jorf'],
            ['id' => 295, 'nom' => 'Jrada'],
            ['id' => 296, 'nom' => 'Kalaat Mgouna'],
            ['id' => 297, 'nom' => 'Jorf El Melha'],
            ['id' => 298, 'nom' => 'Karia Ba Mohamed'],
            ['id' => 299, 'nom' => 'Kandar Sidi Khiar'],
            ['id' => 300, 'nom' => 'Kasba Tadla'],
            ['id' => 301, 'nom' => 'Kattara'],
            ['id' => 302, 'nom' => 'Kechoula'],
            ['id' => 303, 'nom' => 'Ketama'],
            ['id' => 304, 'nom' => 'Khemisset'],
            ['id' => 305, 'nom' => 'Khemisset Chaouia'],
            ['id' => 306, 'nom' => 'Khemis Sidi Yahya'],
            ['id' => 307, 'nom' => 'Khmis Ksiba'],
            ['id' => 308, 'nom' => 'Khouribga'],
            ['id' => 309, 'nom' => 'Khénifra'],
            ['id' => 310, 'nom' => 'Korimate'],
            ['id' => 311, 'nom' => 'Ksabi Moulouya'],
            ['id' => 312, 'nom' => 'Kridid'],
            ['id' => 313, 'nom' => 'Kénitra'],
            ['id' => 314, 'nom' => 'Ksar el-Kebir'],
            ['id' => 315, 'nom' => 'Ksar es-Seghir'],
            ['id' => 316, 'nom' => 'Laaounate'],
            ['id' => 317, 'nom' => 'Laaouama'],
            ['id' => 318, 'nom' => 'Laattaouia'],
            ['id' => 319, 'nom' => 'Laattaouia Ech-Chaybia'],
            ['id' => 320, 'nom' => 'Laatamna'],
            ['id' => 321, 'nom' => 'Laâyoune'],
            ['id' => 322, 'nom' => 'Lagfifat'],
            ['id' => 323, 'nom' => 'Laäyoune Ain Tizgha'],
            ['id' => 324, 'nom' => 'Laghnimyine'],
            ['id' => 325, 'nom' => 'Laghoualem'],
            ['id' => 326, 'nom' => 'Lakhoualqa'],
            ['id' => 327, 'nom' => 'Lagouira'],
            ['id' => 328, 'nom' => 'Lahraouyine'],
            ['id' => 329, 'nom' => 'Lakhnafif'],
            ['id' => 330, 'nom' => 'Lakhiaita'],
            ['id' => 331, 'nom' => 'Lamhadi'],
            ['id' => 332, 'nom' => 'Lakhssas'],
            ['id' => 333, 'nom' => 'Lamaachate'],
            ['id' => 334, 'nom' => 'Lamharza Essahel'],
            ['id' => 335, 'nom' => 'Lamkansa'],
            ['id' => 336, 'nom' => 'Laouamra'],
            ['id' => 337, 'nom' => 'Larache'],
            ['id' => 338, 'nom' => 'Lkhaloua'],
            ['id' => 339, 'nom' => 'Lkheng'],
            ['id' => 340, 'nom' => 'Loulad'],
            ['id' => 341, 'nom' => 'Loudaya'],
            ['id' => 342, 'nom' => 'Louta'],
            ['id' => 343, 'nom' => 'Lqliaa'],
            ['id' => 344, 'nom' => 'Maaziz'],
            ['id' => 345, 'nom' => 'Machraa El Ain'],
            ['id' => 346, 'nom' => 'Madagh'],
            ['id' => 347, 'nom' => 'Majjat'],
            ['id' => 348, 'nom' => 'Mallalienne'],
            ['id' => 349, 'nom' => 'Mansoura'],
            ['id' => 350, 'nom' => 'Marchouch'],
            ['id' => 351, 'nom' => 'Marrakech'],
            ['id' => 352, 'nom' => 'Martil'],
            ['id' => 353, 'nom' => 'Massa'],
            ['id' => 354, 'nom' => 'Méchouar Fès Jdid'],
            ['id' => 355, 'nom' => 'Mdiq'],
            ['id' => 356, 'nom' => 'Mechra Bel Ksiri'],
            ['id' => 357, 'nom' => 'Méchouar Kasba'],
            ['id' => 358, 'nom' => 'Mehdia'],
            ['id' => 359, 'nom' => 'Mediouna'],
            ['id' => 360, 'nom' => 'Meknassa Acharqia'],
            ['id' => 361, 'nom' => 'Meknassa Al Gharbia'],
            ['id' => 362, 'nom' => 'Meknès'],
            ['id' => 363, 'nom' => 'Mers El Kheir'],
            ['id' => 364, 'nom' => 'Mellila'],
            ['id' => 365, 'nom' => 'Merzouga'],
            ['id' => 366, 'nom' => 'Messassa'],
            ['id' => 367, 'nom' => 'Mestegmer'],
            ['id' => 368, 'nom' => 'Mhamid El Ghizlane'],
            ['id' => 369, 'nom' => 'Mestferki'],
            ['id' => 370, 'nom' => 'Midar'],
            ['id' => 371, 'nom' => 'Mhaya'],
            ['id' => 372, 'nom' => 'Mirleft'],
            ['id' => 373, 'nom' => 'Midelt'],
            ['id' => 374, 'nom' => 'Missour'],
            ['id' => 375, 'nom' => 'Mkansa'],
            ['id' => 376, 'nom' => 'Mograne'],
            ['id' => 377, 'nom' => 'Moualine El Oued'],
            ['id' => 378, 'nom' => 'Moulay Abdallah'],
            ['id' => 379, 'nom' => 'Moulay Bouazza'],
            ['id' => 380, 'nom' => 'Moulay Bousselham'],
            ['id' => 381, 'nom' => 'Mohammedia'],
            ['id' => 382, 'nom' => 'Moulay Bouzarqtoune'],
            ['id' => 383, 'nom' => 'Moulay Driss Aghbal'],
            ['id' => 384, 'nom' => 'Moulay Driss Zerhoun'],
            ['id' => 385, 'nom' => 'Mqam Tolba'],
            ['id' => 386, 'nom' => 'Moulay Yaâcoub'],
            ['id' => 387, 'nom' => 'Mrirt'],
            ['id' => 388, 'nom' => 'Msick'],
            ['id' => 389, 'nom' => 'Naima'],
            ['id' => 390, 'nom' => 'Naour'],
            ['id' => 391, 'nom' => 'Nador'],
            ['id' => 392, 'nom' => 'Nkhila'],
            ['id' => 393, 'nom' => 'Ouad Eddahab'],
            ['id' => 394, 'nom' => 'Nouaceur'],
            ['id' => 395, 'nom' => 'Ouahat Sidi Brahim'],
            ['id' => 396, 'nom' => 'Ouaklim'],
            ['id' => 397, 'nom' => 'Oualidia'],
            ['id' => 398, 'nom' => 'Ouaouizeght'],
            ['id' => 399, 'nom' => 'Oualili'],
            ['id' => 400, 'nom' => 'Ouaoumana'],
            ['id' => 401, 'nom' => 'Ouaouzgane'],
            ['id' => 402, 'nom' => 'Ouarzazate'],
            ['id' => 403, 'nom' => 'Ouazzane'],
            ['id' => 404, 'nom' => 'Oued Amlil'],
            ['id' => 405, 'nom' => 'Oued Ifrane'],
            ['id' => 406, 'nom' => 'Oued Jdida'],
            ['id' => 407, 'nom' => 'Oued Malha'],
            ['id' => 408, 'nom' => 'Oued Laou'],
            ['id' => 409, 'nom' => 'Ouirgane'],
            ['id' => 410, 'nom' => 'Oued Zem'],
            ['id' => 411, 'nom' => 'Oujda'],
            ['id' => 412, 'nom' => 'Oukaimden'],
            ['id' => 413, 'nom' => 'Ouislane'],
            ['id' => 414, 'nom' => 'Oulad Abbou'],
            ['id' => 415, 'nom' => 'Oulad Al Toualaa'],
            ['id' => 416, 'nom' => 'Oulad Aissa'],
            ['id' => 417, 'nom' => 'Oulad Dahou'],
            ['id' => 418, 'nom' => 'Oulad Fares'],
            ['id' => 419, 'nom' => 'Oulad Ftata'],
            ['id' => 420, 'nom' => 'Oulad Frej'],
            ['id' => 421, 'nom' => 'Oulad Ghanem'],
            ['id' => 422, 'nom' => 'Oulad Hamdane'],
            ['id' => 423, 'nom' => 'Oulad Mbarek'],
            ['id' => 424, 'nom' => 'Oulad Hcine'],
            ['id' => 425, 'nom' => 'Oulad Mrah'],
            ['id' => 426, 'nom' => 'Oulad Mtaa'],
            ['id' => 427, 'nom' => 'Oulad Said'],
            ['id' => 428, 'nom' => 'Oulad Said Loued'],
            ['id' => 429, 'nom' => 'Oulad Yahya Louta'],
            ['id' => 430, 'nom' => 'Oulad Salah'],
            ['id' => 431, 'nom' => 'Oulad Yaich'],
            ['id' => 432, 'nom' => 'Oulad Youssef'],
            ['id' => 433, 'nom' => 'Oulad Zidane'],
            ['id' => 434, 'nom' => 'Ouled Berhil'],
            ['id' => 435, 'nom' => 'Ouled Ayad'],
            ['id' => 436, 'nom' => 'Ouled Dlim'],
            ['id' => 437, 'nom' => 'Ouled Frej'],
            ['id' => 438, 'nom' => 'Ouled Teïma'],
            ['id' => 439, 'nom' => 'Oulmes'],
            ['id' => 440, 'nom' => 'Ounagha'],
            ['id' => 441, 'nom' => 'Ourika'],
            ['id' => 442, 'nom' => 'Outat El Haj'],
            ['id' => 443, 'nom' => 'Rabat'],
            ['id' => 444, 'nom' => 'Ras Ain Rhamna'],
            ['id' => 445, 'nom' => 'Ras El Ain'],
            ['id' => 446, 'nom' => 'Ras Ijerri'],
            ['id' => 447, 'nom' => 'Ratba'],
            ['id' => 448, 'nom' => 'Rfala'],
            ['id' => 449, 'nom' => 'Rima'],
            ['id' => 450, 'nom' => 'Ribat el Kheir'],
            ['id' => 451, 'nom' => 'Rissana Janoubia'],
            ['id' => 452, 'nom' => 'Rommani'],
            ['id' => 453, 'nom' => 'Rissani'],
            ['id' => 454, 'nom' => 'Saada'],
            ['id' => 455, 'nom' => 'Saadla'],
            ['id' => 456, 'nom' => 'Sabaa Aiyoun'],
            ['id' => 457, 'nom' => 'Safi'],
            ['id' => 458, 'nom' => 'Sabbah'],
            ['id' => 459, 'nom' => 'Sahel Chamali'],
            ['id' => 460, 'nom' => 'Sahel Oulad Hriz'],
            ['id' => 461, 'nom' => 'Saidia'],
            ['id' => 462, 'nom' => 'Salé'],
            ['id' => 463, 'nom' => 'Saka'],
            ['id' => 464, 'nom' => 'Sbouya'],
            ['id' => 465, 'nom' => 'Sebt Gzoula'],
            ['id' => 466, 'nom' => 'Sebt Ennabour'],
            ['id' => 467, 'nom' => 'Sefrou'],
            ['id' => 468, 'nom' => 'Selouane'],
            ['id' => 469, 'nom' => 'Settat'],
            ['id' => 470, 'nom' => 'Sidi Abdallah El Bouchouari'],
            ['id' => 471, 'nom' => 'Sfassif'],
            ['id' => 472, 'nom' => 'Sidi Abderrazak'],
            ['id' => 473, 'nom' => 'Sidi Abdallah Ghiat'],
            ['id' => 474, 'nom' => 'Sidi Abed'],
            ['id' => 475, 'nom' => 'Sidi Aissa Ben Ali'],
            ['id' => 476, 'nom' => 'Sidi Ahmed Ou Amar'],
            ['id' => 477, 'nom' => 'Sidi Ali'],
            ['id' => 478, 'nom' => 'Sidi Aissa Ben Slimane'],
            ['id' => 479, 'nom' => 'Sidi Ali Ben Hamdouche'],
            ['id' => 480, 'nom' => 'Sidi Allal Tazi'],
            ['id' => 481, 'nom' => 'Sidi Allal El Bahraoui'],
            ['id' => 482, 'nom' => 'Sidi Bennour'],
            ['id' => 483, 'nom' => 'Sidi Bettache'],
            ['id' => 484, 'nom' => 'Sidi Bibi'],
            ['id' => 485, 'nom' => 'Sidi Boaal'],
            ['id' => 486, 'nom' => 'Sidi Boukhalkhal'],
            ['id' => 487, 'nom' => 'Sidi Boubker'],
            ['id' => 488, 'nom' => 'Sidi Bouknadel'],
            ['id' => 489, 'nom' => 'Sidi Boulenouar'],
            ['id' => 490, 'nom' => 'Sidi Bou Othmane'],
            ['id' => 491, 'nom' => 'Sidi Boumehdi'],
            ['id' => 492, 'nom' => 'Sidi Chiker'],
            ['id' => 493, 'nom' => 'Sidi Dahbi'],
            ['id' => 494, 'nom' => 'Sidi Bouzid'],
            ['id' => 495, 'nom' => 'Sidi El Abed'],
            ['id' => 496, 'nom' => 'Sidi el Aîdi'],
            ['id' => 497, 'nom' => 'Sidi El Makhfi'],
            ['id' => 498, 'nom' => 'Sidi El Mekki'],
            ['id' => 499, 'nom' => 'Sidi Hajjaj'],
            ['id' => 500, 'nom' => 'Sidi Hajjaj Oued Hassar'],
            ['id' => 501, 'nom' => 'Sidi Jaber'],
            ['id' => 502, 'nom' => 'Sidi Ifni'],
            ['id' => 503, 'nom' => 'Sidi Lyamani'],
            ['id' => 504, 'nom' => 'Sidi Kacem'],
            ['id' => 505, 'nom' => 'Sidi Moussa Ben Ali'],
            ['id' => 506, 'nom' => 'Sidi Moussa El Majdoub'],
            ['id' => 507, 'nom' => 'Sidi Ouassay'],
            ['id' => 508, 'nom' => 'Sidi Rahal'],
            ['id' => 509, 'nom' => 'Sidi Slimane'],
            ['id' => 510, 'nom' => 'Sidi Smail'],
            ['id' => 511, 'nom' => 'Sidi Taibi'],
            ['id' => 512, 'nom' => 'Sidi Slimane Echcharraa'],
            ['id' => 513, 'nom' => 'Sidi Yahya'],
            ['id' => 514, 'nom' => 'Sidi Yahya El Gharb'],
            ['id' => 515, 'nom' => 'Sidi Yahya Zaer'],
            ['id' => 516, 'nom' => 'Sid Lmokhtar'],
            ['id' => 517, 'nom' => 'Sid Zouine'],
            ['id' => 518, 'nom' => 'Skhinate'],
            ['id' => 519, 'nom' => 'Skhirat'],
            ['id' => 520, 'nom' => 'Skhour Rhamna'],
            ['id' => 521, 'nom' => 'Skoura Ahl El Oust'],
            ['id' => 522, 'nom' => 'Skoura Mdaz'],
            ['id' => 523, 'nom' => 'Souaken'],
            ['id' => 524, 'nom' => 'Smia'],
            ['id' => 525, 'nom' => 'Souihla'],
            ['id' => 526, 'nom' => 'Souk El Arbaa'],
            ['id' => 527, 'nom' => 'Souk Sebt Ouled Nemma'],
            ['id' => 528, 'nom' => 'Souk Tlet El Gharb'],
            ['id' => 529, 'nom' => 'Tabant'],
            ['id' => 530, 'nom' => 'Steha'],
            ['id' => 531, 'nom' => 'Tabouda'],
            ['id' => 532, 'nom' => 'Tachraft'],
            ['id' => 533, 'nom' => 'Tafersit'],
            ['id' => 534, 'nom' => 'Tafoughalt'],
            ['id' => 535, 'nom' => 'Tagante'],
            ['id' => 536, 'nom' => 'Tadighoust'],
            ['id' => 537, 'nom' => 'Tafraout'],
            ['id' => 538, 'nom' => 'Taghzout'],
            ['id' => 539, 'nom' => 'Taghazout'],
            ['id' => 540, 'nom' => 'Taghzoute Nait Atta'],
            ['id' => 541, 'nom' => 'Tahannaout'],
            ['id' => 542, 'nom' => 'Takate'],
            ['id' => 543, 'nom' => 'Tahla'],
            ['id' => 544, 'nom' => 'Talmakante'],
            ['id' => 545, 'nom' => 'Talat Nyaaqoub'],
            ['id' => 546, 'nom' => 'Taliouine'],
            ['id' => 547, 'nom' => 'Talmest'],
            ['id' => 548, 'nom' => 'Talsint'],
            ['id' => 549, 'nom' => 'Tamallalt'],
            ['id' => 550, 'nom' => 'Tamaris'],
            ['id' => 551, 'nom' => 'Tamensourt'],
            ['id' => 552, 'nom' => 'Tameslohte'],
            ['id' => 553, 'nom' => 'Tamazouzte'],
            ['id' => 554, 'nom' => 'Tamedit'],
            ['id' => 555, 'nom' => 'Tamorot'],
            ['id' => 556, 'nom' => 'Tamezmoute'],
            ['id' => 557, 'nom' => 'Tamesna'],
            ['id' => 558, 'nom' => 'Tamouda Bay'],
            ['id' => 559, 'nom' => 'Tamri'],
            ['id' => 560, 'nom' => 'Tanant'],
            ['id' => 561, 'nom' => 'Tanger'],
            ['id' => 562, 'nom' => 'Tamsaout'],
            ['id' => 563, 'nom' => 'Tangarfa'],
            ['id' => 564, 'nom' => 'Taounate'],
            ['id' => 565, 'nom' => 'Tan-Tan'],
            ['id' => 566, 'nom' => 'Taourirt'],
            ['id' => 567, 'nom' => 'Tarfaya'],
            ['id' => 568, 'nom' => 'Targuist'],
            ['id' => 569, 'nom' => 'Taroudant'],
            ['id' => 570, 'nom' => 'Tata'],
            ['id' => 571, 'nom' => 'Tataoute'],
            ['id' => 572, 'nom' => 'Tatoft'],
            ['id' => 573, 'nom' => 'Tassoultante'],
            ['id' => 574, 'nom' => 'Taza'],
            ['id' => 575, 'nom' => 'Tazemmourt'],
            ['id' => 576, 'nom' => 'Taznakht'],
            ['id' => 577, 'nom' => 'Tazart'],
            ['id' => 578, 'nom' => 'Temara'],
            ['id' => 579, 'nom' => 'Temsamane'],
            ['id' => 580, 'nom' => 'Temsia'],
            ['id' => 581, 'nom' => 'Tendrara'],
            ['id' => 582, 'nom' => 'Tichla'],
            ['id' => 583, 'nom' => 'Thar Es-Souk'],
            ['id' => 584, 'nom' => 'Tiddas'],
            ['id' => 585, 'nom' => 'Tighirt'],
            ['id' => 586, 'nom' => 'Tétouan'],
            ['id' => 587, 'nom' => 'Tifarouine'],
            ['id' => 588, 'nom' => 'Tikiouine'],
            ['id' => 589, 'nom' => 'Tifelt'],
            ['id' => 590, 'nom' => 'Timoulay'],
            ['id' => 591, 'nom' => 'Timahdite'],
            ['id' => 592, 'nom' => 'Tit Mellil'],
            ['id' => 593, 'nom' => 'Timoulilt'],
            ['id' => 594, 'nom' => 'Tlite'],
            ['id' => 595, 'nom' => 'Tiznit'],
            ['id' => 596, 'nom' => 'Touama'],
            ['id' => 597, 'nom' => 'Tinejdad'],
            ['id' => 598, 'nom' => 'Tissa'],
            ['id' => 599, 'nom' => 'Tinghir'],
            ['id' => 600, 'nom' => 'Youssoufia'],
            ['id' => 601, 'nom' => 'Tsaft'],
            ['id' => 602, 'nom' => 'Tnine Aglou'],
            ['id' => 603, 'nom' => 'Touissit'],
            ['id' => 604, 'nom' => 'Tizgane'],
            ['id' => 605, 'nom' => 'Zag'],
            ['id' => 606, 'nom' => 'Zaïo'],
            ['id' => 607, 'nom' => 'Zaouïat Cheikh'],
            ['id' => 608, 'nom' => 'Zagora'],
            ['id' => 609, 'nom' => 'Zaouia Sidi Tahar'],
            ['id' => 610, 'nom' => 'Zaouiat Sidi Kacem'],
            ['id' => 611, 'nom' => 'Zemamra'],
            ['id' => 612, 'nom' => 'Zemrane'],
            ['id' => 613, 'nom' => 'Zaida'],
            ['id' => 614, 'nom' => 'Zenata'],
            ['id' => 615, 'nom' => 'Zeghanghane'],
            ['id' => 616, 'nom' => 'Zoumi'],
            ['id' => 617, 'nom' => 'Zoug'],
            ['id' => 618, 'nom' => 'Ziaida'],
            ['id' => 619, 'nom' => 'NZalat Bni Amar'],
            ['id' => 620, 'nom' => 'Dlalha'],
            ['id' => 621, 'nom' => 'Bni Ahmed Gharbia'],
            ['id' => 622, 'nom' => 'Sidi Yahya Ou Saad'],
            ['id' => 623, 'nom' => 'Ayacha'],
        ]);
    }
}
